import type { Metadata } from "next";
// import Provider from "@/components/Provider";
import "@/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
        {/* <Provider>{children}</Provider> */}
      </body>
    </html>
  );
}
